### ISSUE TITLE
PAPI and text color in Titles

### ISSUE THREAD

**Issue by mrsqueak11806** [Frcsty/FrozenJoin#25]
The plugin isn't displaying text colors or parsing placeholders that are used in the title screen or the action bar.

ex. &6Competitors %essentials_nickname% 

shows up exactly like that instead of gold text reading "Competitors MrSqueak the Admin"

**Comment by BlitzOffline** [comment]
Hello. I know its been a while but any chance this still happens? If so what version of FrozenJoin are you using? And are you willing to use a dev build to see if it still happens? because I believe I fixed this quite a while ago but there was no spigot release since then and I just want to make sure. If you are willing to use a development build then you can download it from here: https://www.dropbox.com/s/xha7ntkmnv6olao/FrozenJoin-2.3.0.jar?dl=0

**Comment by Frcsty** [comment]
Since no response, issue not existent I guess
